modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL=""

[[mods]]
    modId="catowers"
    version="${file.jarVersion}"
    displayName="CA Towers"
    #updateJSONURL=""
    authors="Grimmauld"
    description='''
Some cool description'''

[[dependencies.catowers]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.catowers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"